send_command:
  target:
    entity:
      domain: button
  fields:
    command_type:
      required: true
      example: "rf"
      default: "rf"
      selector:
        select:
          options:
            - "rf"
            - "ir"
    command_code:
      required: true
      selector:
        text:
